name: MCPacketLibrary
version: 1.1
description: Minecraft Packet Handling Library for Spigot
authors: [Krymonota, CraftAPI]
website: https://craftapi.com
main: com.craftapi.mcpacketlibrary.MCPacketLibrary