name: MCPacketLibrary
version: 1.1
description: Minecraft Packet Handling Library for Spigot
author: Krymonota
website: https://krymonota.github.io
main: io.github.krymonota.mcpacketlibrary.MCPacketLibrary