name: MCPacketLibrary
version: 1.0
description: Minecraft Packet Handling Library for Bukkit/Spigot
authors: [Krymonota, CraftAPI]
website: http://craftapi.com
main: com.craftapi.mcpacketlibrary.MCPacketLibrary